name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3

      - name: Decode keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > keystore.jks
          echo "MYAPP_UPLOAD_STORE_FILE=keystore.jks" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build release artifacts
        run: |
          ./gradlew --no-daemon clean \
            $([[ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]] && echo "assembleRelease bundleRelease" || echo "assembleRelease bundleRelease")

      - name: Upload build outputs (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/bundle/release/*.aab

      - name: Create/Update GitHub Release and attach assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
